baseURL = "https://dossaj.github.io/cv-site/"
languageCode = "en"
title = "Curriculum Vitae"
theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]
author = "Jason Dos Santos"
description = "Curriculum Vitae for Jason Dos Santos"
styles = "styles-custom.css"
title = "Curriculum Vitae"

[params.profile]
name = "Jason Dos Santos"
tagline = "Full Stack Developer"
avatar = "avatar-small.png"

# Contact section
[params.contact]
enable = true

[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto: jason.dos.santos@outlook.com"
title = "jason.dos.santos@outlook.com"

[[params.contact.list]]
class = "linkedin"
icon = "fa-linkedin"
url = "//linkedin.com/in/jason-dos-santos-6b219019"
title = "linkedin/jason-dos-santos"

[[params.contact.list]]
class = "github"
icon = "fa-github"
url = "//github.com/dossaj"
title = "github.com/dossaj"

# Education section
[params.education]
enable = true
title = "Education"

[[params.education.list]]
degree = "BSc in Computer Science"
college = "University of Johannesburg"
dates = "2004 - 2006"

# Languages section
[params.language]
enable = true
title = "Languages"

[[params.language.list]]
language = "English"
level = "Native"

# Interests section
[params.interests]
enable = true
title = "Interests"

[[params.interests.list]]
interest = "3D Printing"

[[params.interests.list]]
interest = "Motor Racing"

[[params.interests.list]]
interest = "Gaming"

[[params.interests.list]]
interest = "Biking"

[[params.interests.list]]
interest = "Music"

[[params.interests.list]]
interest = "Sports"

# Main body sections

# You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

# Summary section
[params.summary]
enable = true
icon = "fa-user"
title = "Career Profile"
summary = "Software professional with a focus in software engineering. Experienced in software and system architecture, cloud systems, continuous integration/delivery and working with agile methodologies."

#Take pride in work
#striving for excellence
#work hard and play hard
#lead by example 
#analytical 


#Calculated risk-taker, relentlessly goal-driven, paying ruthless attention to detail and striving for excellence in all aspects of my professional work. Huge believer in leading by example, a philosophy I have utilised to effectively manage/influence high performing teams. Motivated team member who is able to work and communicate effectively with people of varying skill/communication levels."

# Experiences section
[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Experiences"

[[params.jobs.list]]
position = "Principal Developer / System Architect"
dates = "2018 - Present"
company = "Fisher & Paykel Healthcare, Auckland"
details = "/content/experiences/fnp.md"

[[params.jobs.list]]
position = "Intermediate Software Developer"
dates = "2010 - 2012"
company = "Triquestra International, Auckland"
details = "/content/experiences/triquestra.md"

[[params.jobs.list]]
position = "Software Developer"
dates = "2008 - 2010"
company = "Cortell New Zealand, Auckland"
details = "/content/experiences/cortell.md"

# Projects section
[params.projects]
enable = true
icon = "fa-archive"
title = "Projects"
intro = "Overview of the personal projects hosted on [GitHub](//github.com/dossaj).<br/>N.B. Not all personal projects have been pushed to GitHub"

[[params.projects.list]]
title = "Marlin"
url = "https://github.com/dossaj/Marlin"
tagline = "Fork of the Marlin firmware. This fork provides customised versions of the printer firmware, with configurations for RepRap printers built from the ground up. This also includes some changes for configurable homing currents, for TMC2130 drivers."

[[params.projects.list]]
title = "DrawIO Export Cli"
url = "https://github.com/dossaj/drawio-export-cli"
tagline = "NPM package exposing export functionality for DrawIO export via a command line interface. This package exports the drawing as an SVG, allowing the export to be scripted as part of a NPM build. It is used by a documentation framework which provides DrawIO integration."

[[params.projects.list]]
title = "OpenSCAD Parts"
url = "https://github.com/dossaj/parts-scad"
tagline = "Repository containing the source for OpenSCAD parts created for RepRap printers. The source is published along with the STL for direct download. STL's can also be viewed on GitHub directly."

[[params.projects.list]]
title = "CV Documentation"
url = "https://github.com/dossaj/cv-docs"
tagline = "Repository for the source of this CV site. Site is built using the static site generator, Hugo. Continuous integration has been setup using Travis CI."

[[params.projects.list]]
title = "CV Site"
url = "https://github.com/dossaj/cv-site"
tagline = "Repository to host the published files for the CV project. This repository is setup using GitHub pages. This repository exists to keep the separation of source code and published content."

# Skills section
[params.skills]
enable = true
icon = "fa-rocket"
title = "Skills & Proficiency"

[[params.skills.list]]
skill = "C#"
level = "85%"

[[params.skills.list]]
skill = "C++"
level = "70%"

[[params.skills.list]]
skill = "ASP.NET / ASP.NET Core"
level = "80%"

[[params.skills.list]]
skill = "SQL Server"
level = "80%"

[[params.skills.list]]
skill = "JavaScript & jQuery"
level = "80%"

[[params.skills.list]]
skill = "HTML5 & CSS"
level = "80%"

[[params.skills.list]]
skill = "Networking & Infrastructure"
level = "80%"

[[params.skills.list]]
skill = "Hugo"
level = "75%"

[[params.skills.list]]
skill = "WPF/WCF"
level = "75%"

[[params.skills.list]]
skill = "Redis"
level = "75%"

[[params.skills.list]]
skill = "RabbitMQ"
level = "75%"

[[params.skills.list]]
skill = "Docker"
level = "60%"

[[params.skills.list]]
skill = "Angular"
level = "50%"

[[params.skills.list]]
skill = "Kubernetes"
level = "30%"

# Footer section

# The original template is released under the Creative Commons Attribution 3.0 License.
# Please keep the original attribution link when using for your own project.
# If you'd like to use the template without the attribution,
# you can check out other license options via template author's website: themes.3rdwavemedia.com
# 
# As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

[params.footer]
copyright = ""