version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

jobs:
  deploy:
    docker:
      - image: cimg/deploy:2023.02
    steps:
      - attach_workspace:
          at: cv-site
      - checkout
      - run: ls -lah cv-site
      - run: ls -lah .
      - run:
          name: deploy
          command: bash deploy.sh

workflows:
  build-workflow:
    jobs:
      - hugo/build:
          html-proofer: false
          version: '0.52'
      - deploy:
          # filters:
          #   branches:
          #     only: master
          requires:
            - hugo/build