version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: |
            .circleci/deploy.sh
orbs:
  hugo: circleci/hugo@0.2
workflows:
  build-workflow:
    jobs:
      - hugo/build:
          html-proofer: true
          source: /
          version: '0.52'
      - deploy:
          # filters:
          #   branches:
          #     only: master
          requires:
            - hugo/build