version: 2.1

orbs:
  hugo: circleci/hugo@1.3.0

jobs:
  deploy:
    docker:
      - image: cimg/deploy:2023.02
        user: root
    steps:
      - run:
          name: Make source directory
          command: mkdir src
      - checkout:
          path: src
      - attach_workspace:
          at: src
      - run:
          name: deploy
          command: cd src && bash deploy.sh

workflows:
  build-workflow:
    jobs:
      - hugo/build:
          html-proofer: false
          version: '0.52'
      - deploy:
          # filters:
          #   branches:
          #     only: master
          requires:
            - hugo/build